# Generated by Django 5.0.4 on 2024-07-23 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mnappli', '0002_alter_book_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Auteur', 'verbose_name_plural': 'Auteurs'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Livre', 'verbose_name_plural': 'Livres'},
        ),
    ]
